services:
  - name: ml-api
    type: web
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
